version: "3.9"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: ROOTUSER123
    volumes:
      - ~/minio/data:/data
    ports:
      - "${MINIO_CONSOLE}:9000"
      - "${MINIO_HTTP}:9090"
    command: server /data --console-address ":9090"
